services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminTrung
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
